In [38]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\chaitu\anaconda3\lib\site-packages (2.9.12)

In [39]:
#Cell 1 - Imports

import os
import pandas as pd
from sqlalchemy import create_engine

In [40]:
#Cell 2 - Database connection

from urllib.parse import quote_plus

DB_USER = "postgres"
DB_PASSWORD = quote_plus("Yaniv305@#")  
DB_HOST = "localhost"
DB_PORT = 5432
DB_NAME = "torus_db"

connection_string = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

connection_string

'postgresql+psycopg2://postgres:Yaniv305%40%23@localhost:5432/torus_db'

In [43]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
from urllib.parse import quote_plus
from datetime import datetime, timedelta

DB_PASSWORD = quote_plus("Yaniv305@#") 
engine = create_engine(f"postgresql+psycopg2://postgres:{DB_PASSWORD}@localhost:5432/torus_db")

np.random.seed(42)
n_patients = 300

patients_df = pd.DataFrame({
    "patient_id": range(1, n_patients + 1),
    "age": np.random.randint(18, 85, n_patients),
    "sex": np.random.choice(["M", "F"], n_patients),
    "risk_category": np.random.choice(["low", "medium", "high"], n_patients, p=[0.5, 0.35, 0.15]),
})

n_exams = 800
exam_ids = range(1, n_exams + 1)
patient_ids_for_exams = np.random.choice(patients_df["patient_id"], n_exams)
devices = ["DEV-001", "DEV-002", "DEV-003", "DEV-004"]
exam_types = ["abdominal", "cardiac", "obstetric", "vascular"]
outcomes = ["normal", "follow_up_required", "inconclusive"]

start_date = datetime(2025, 1, 1)
exam_timestamps = [start_date + timedelta(days=int(x)) for x in np.random.randint(0, 500, n_exams)]

exams_df = pd.DataFrame({
    "exam_id": exam_ids,
    "patient_id": patient_ids_for_exams,
    "device_id": np.random.choice(devices, n_exams),
    "exam_type": np.random.choice(exam_types, n_exams),
    "exam_timestamp": exam_timestamps,
    "image_quality_score": np.round(np.random.uniform(0.5, 1.0, n_exams), 2),
    "outcome_label": np.random.choice(outcomes, n_exams, p=[0.65, 0.25, 0.10]),
})

from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS ultrasound_exams CASCADE;"))
    conn.execute(text("DROP TABLE IF EXISTS patients CASCADE;"))
    conn.commit()

print("Old tables dropped.")

Old tables dropped.

In [44]:
patients_df.to_sql("patients", engine, if_exists="append", index=False)
exams_df.to_sql("ultrasound_exams", engine, if_exists="append", index=False)

print("Inserted patients:", len(patients_df))
print("Inserted exams:", len(exams_df))

Inserted patients: 300
Inserted exams: 800

In [45]:
check1 = pd.read_sql_query("SELECT COUNT(*) AS cnt FROM patients;", engine)
check2 = pd.read_sql_query("SELECT COUNT(*) AS cnt FROM ultrasound_exams;", engine)
print("patients rows:", check1["cnt"][0])
print("ultrasound_exams rows:", check2["cnt"][0])

patients rows: 300
ultrasound_exams rows: 800

In [46]:
engine = create_engine(connection_string)
engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/torus_db)

In [47]:
#Cell 3 - SQL query

modeling_sql = """
SELECT
    e.exam_id,
    e.patient_id,
    p.age,
    p.sex,
    p.risk_category,
    e.device_id,
    e.exam_type,
    e.exam_timestamp,
    e.image_quality_score,
    e.outcome_label,
    CASE
        WHEN e.outcome_label = 'follow_up_required' THEN 1
        ELSE 0
    END AS target
FROM ultrasound_exams e
JOIN patients p
    ON e.patient_id = p.patient_id;
"""

In [48]:
#Cell 4 - Load data

modeling_df = pd.read_sql_query(modeling_sql, engine)
modeling_df.head()

,exam_id,patient_id,age,sex,risk_category,device_id,exam_type,exam_timestamp,image_quality_score,outcome_label,target
0,1,78,80,F,medium,DEV-003,obstetric,2025-07-04,0.88,normal,0
1,2,62,65,F,low,DEV-001,obstetric,2025-02-08,0.98,inconclusive,0
2,3,132,18,F,low,DEV-004,obstetric,2025-08-11,0.85,inconclusive,0
3,4,89,51,M,medium,DEV-002,vascular,2025-07-03,0.65,normal,0
4,5,237,25,M,low,DEV-003,abdominal,2026-05-10,0.55,normal,0

In [49]:
#Cell 5 - Sanity checks

print("Shape:", modeling_df.shape)

print("\nMissing values per column:")
print(modeling_df.isnull().sum())

print("\nTarget distribution:")
print(modeling_df["target"].value_counts())

print("\nTarget distribution (normalized):")
print(modeling_df["target"].value_counts(normalize=True))

Shape: (800, 11)

Missing values per column:
exam_id                0
patient_id             0
age                    0
sex                    0
risk_category          0
device_id              0
exam_type              0
exam_timestamp         0
image_quality_score    0
outcome_label          0
target                 0
dtype: int64

Target distribution:
target
0    602
1    198
Name: count, dtype: int64

Target distribution (normalized):
target
0    0.7525
1    0.2475
Name: proportion, dtype: float64

In [50]:
#Cell 6 - Data types check

modeling_df.dtypes

exam_id                         int64
patient_id                      int64
age                             int64
sex                            object
risk_category                  object
device_id                      object
exam_type                      object
exam_timestamp         datetime64[ns]
image_quality_score           float64
outcome_label                  object
target                          int64
dtype: object

In [51]:
#Cell 7 - Basic descriptive stats

modeling_df.describe(include="all")

,exam_id,patient_id,age,sex,risk_category,device_id,exam_type,exam_timestamp,image_quality_score,outcome_label,target
count,800.0000,800.000000,800.000000,800,800,800,800,800,800.000000,800,800.00000
unique,NaN,NaN,NaN,2,3,4,4,NaN,NaN,3,NaN
top,NaN,NaN,NaN,F,low,DEV-004,abdominal,NaN,NaN,normal,NaN
freq,NaN,NaN,NaN,413,421,216,219,NaN,NaN,529,NaN
mean,400.5000,149.058750,51.195000,NaN,NaN,NaN,NaN,2025-09-12 06:57:36,0.748738,NaN,0.24750
min,1.0000,1.000000,18.000000,NaN,NaN,NaN,NaN,2025-01-01 00:00:00,0.500000,NaN,0.00000
25%,200.7500,72.750000,34.000000,NaN,NaN,NaN,NaN,2025-05-11 12:00:00,0.620000,NaN,0.00000
50%,400.5000,152.000000,50.000000,NaN,NaN,NaN,NaN,2025-09-15 12:00:00,0.750000,NaN,0.00000
75%,600.2500,225.250000,71.000000,NaN,NaN,NaN,NaN,2026-01-20 00:00:00,0.870000,NaN,0.00000
max,800.0000,300.000000,84.000000,NaN,NaN,NaN,NaN,2026-05-15 00:00:00,1.000000,NaN,1.00000
std,231.0844,88.716888,20.435484,NaN,NaN,NaN,NaN,NaN,0.144381,NaN,0.43183

In [52]:
#Cell 8 - Save processed dataset

os.makedirs("data/processed", exist_ok=True)

output_path = "data/processed/modeling_dataset.csv"
modeling_df.to_csv(output_path, index=False)

print(f"Saved modeling dataset to {output_path}")

Saved modeling dataset to data/processed/modeling_dataset.csv

In [53]:
#Cell 9 - Feature/target preview (optional)

feature_cols = [
    "age",
    "sex",
    "risk_category",
    "device_id",
    "exam_type",
    "image_quality_score",
]

X = modeling_df[feature_cols]
y = modeling_df["target"]

print("Feature matrix shape:", X.shape)
print("Target vector shape:", y.shape)

X.head()

Feature matrix shape: (800, 6)
Target vector shape: (800,)

   age sex risk_category device_id  exam_type  image_quality_score
0   80   F        medium   DEV-003  obstetric                 0.88
1   65   F           low   DEV-001  obstetric                 0.98
2   18   F           low   DEV-004  obstetric                 0.85
3   51   M        medium   DEV-002   vascular                 0.65
4   25   M           low   DEV-003  abdominal                 0.55

In [54]:
#Cell 10 - Verify saved file loads correctly

check_df = pd.read_csv("data/processed/modeling_dataset.csv")
check_df.head()

,exam_id,patient_id,age,sex,risk_category,device_id,exam_type,exam_timestamp,image_quality_score,outcome_label,target
0,1,78,80,F,medium,DEV-003,obstetric,2025-07-04,0.88,normal,0
1,2,62,65,F,low,DEV-001,obstetric,2025-02-08,0.98,inconclusive,0
2,3,132,18,F,low,DEV-004,obstetric,2025-08-11,0.85,inconclusive,0
3,4,89,51,M,medium,DEV-002,vascular,2025-07-03,0.65,normal,0
4,5,237,25,M,low,DEV-003,abdominal,2026-05-10,0.55,normal,0